### ISSUE TITLE
你好，请问哪里可以获取训练数据

### ISSUE THREAD

**Issue by hao297531173** [imagecbj/A-serial-image-copy-move-forgery-localization-scheme-with-source-target-distinguishment#2]

**Comment by 170744039** [comment]
我有陈老师在论文中所提及的busternet原数据集，也就是论文中所采用的训练及测试数据集，但我在复现他的第一阶段时始终无法将模型训练到论文中最后的收敛精度，而且差的很远。在排除一系列差异后，只有在对于训练数据集的处理上存在区别。原数据集是LMDB格式，我是将其读取成bmp格式的图片再转成tfrecord形式进行训练，没有采用陈老师的处理方法，我可以将数据集分享给你，并共同探讨一下关于它的处理问题。
