### ISSUE TITLE
您好！我在代码复现过程中，运行创建数据集的代码时遇到错误

### ISSUE THREAD

**Issue by uuhh25** [imagecbj/A-serial-image-copy-move-forgery-localization-scheme-with-source-target-distinguishment#6]
您好，我在运行您关于创建数据集的代码时，提示缺失 mask 文件，请问您能够补充 casia 这个数据集的annotation_file 吗？

![image](https://user-images.githubusercontent.com/50958380/144860257-793d5e96-3210-4c2a-b8ae-86f7b4d019b3.png)

感谢您在百忙中的回复！

**Comment by 170744039** [comment]
> 您好，我在运行您关于创建数据集的代码时，提示缺失 mask 文件，请问您能够补充 casia 这个数据集的annotation_file 吗？
> 
> ![image](https://user-images.githubusercontent.com/50958380/144860257-793d5e96-3210-4c2a-b8ae-86f7b4d019b3.png)
> 
> 感谢您在百忙中的回复！

你好，我也在复现这篇论文以及busternet，可以交流一下吗？我的QQ2978064409
